name = "stock-watchlist-proxy"
main = "worker.js"
compatibility_date = "2024-11-01"

[observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "VISITS"
id = "b8cc30b1012548afb2cd21a5749a7c62"
